---
title: Título
author:
 - name: Alejandro León Líndez
   affil: 1
 - name: Adrian Lizzadro Pla
   affil: 2
 - name: Marta Medina Muñiz
   affil: 3
affiliation:
  - num: 1
    address: |
      Máster en Ciencia de Datos
    email: alelin@alumni.uv.es
  - num: 2
    address: |
      Máster en Ciencia de Datos
    email: alizpla@alumni.uv.es
  - num: 3
    address: |
      Máster en Ciencia de Datos
    email: memuiz@alumni.uv.es

# document options
journal: notspecified
type: article
status: submit
# front matter
simplesummary: |
  Resumen.
abstract: |
  Abstract
# back matter
keywords: |
  keyword 1; keyword 2; keyword 3 (list three to ten pertinent keywords specific 
                                   to the article, yet reasonably common within the subject discipline.).


abbreviations:
  - short: MDPI
    long: Multidisciplinary Digital Publishing Institute
  - short: DOAJ
    long: Directory of open access journals
  - short: TLA
    long: Three letter acronym
  - short: LD 
    long: linear dichroism
bibliography: mybibfile.bib
appendix: appendix.tex
endnotes: false
output: 
  rticles::mdpi_article:
  extra_dependencies: longtable
---

```{r setup, include=FALSE}
# Setup Chunk
library(here)
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here()) # Set working directory a la carpeta del proyecto en lugar de a la sub-cartpeta del Rmd
```

# Introducción

# Carga de librerías e importación del fichero

```{r}
rm(list=ls())  # Borrar todas las variables al principio
```

```{r}
library(readr)
library(ggplot2)
```

```{r}
gastos <- read_delim("data/Gasto_turistas_internacionales_segun_comunidad_paisresidencia.csv",  delim = ";", escape_double = FALSE, trim_ws = TRUE)
```
## Transformacion a tidy data
```{r}
tipos_datos <- unique(gastos$`Gastos y duración media de los viajes`)
tipos_datos
```
```{r}
gastos1 <- subset(gastos,gastos$`Gastos y duración media de los viajes`== tipos_datos[1])
colnames(gastos1)[colnames(gastos1)=="Total"]<- "Gasto_total"
gastos1<- subset(gastos1, select = -`Gastos y duración media de los viajes`)
```


```{r}
gastos2 <- subset(gastos,gastos$`Gastos y duración media de los viajes`== tipos_datos[2])
colnames(gastos2)[colnames(gastos2)=="Total"]<- "Gasto_medio_persona"
gastos2<- subset(gastos2, select = -`Gastos y duración media de los viajes`)
```

```{r}
gastos3 <- subset(gastos,gastos$`Gastos y duración media de los viajes`== tipos_datos[3])
colnames(gastos3)[colnames(gastos3)=="Total"]<- "Gasto_medio_diario_persona"
gastos3<- subset(gastos3, select = -`Gastos y duración media de los viajes`)
```

```{r}
gastos4 <- subset(gastos,gastos$`Gastos y duración media de los viajes`== tipos_datos[4])
colnames(gastos4)[colnames(gastos4)=="Total"]<- "Duracion_media"
gastos4<- subset(gastos4, select = -`Gastos y duración media de los viajes`)
```

```{r}

# Compruebo que en todas las columnas salvo la última todos las filas son iguales para poder hacer merge de los dos datasets correctamente
any(gastos1[1:length(nrow(gastos1)-1)] !=gastos2[1:length(nrow(gastos2)-1)])
any(gastos3[1:length(nrow(gastos1)-1)] !=gastos4[1:length(nrow(gastos2)-1)])

```

```{r}
# Uno los dos datasets en un único dataset con el que trabajar

gastos12 <- merge(gastos1,gastos2, by = c(colnames(gastos1[1:length(gastos1)-1])))
gastos34 <- merge(gastos3,gastos4, by = c(colnames(gastos3[1:length(gastos3)-1])))
```

```{r}
# Compruebo que en todas las columnas salvo la última todos las filas son iguales para poder hacer merge de los dos datasets correctamente
any(gastos12[1:length(nrow(gastos12)-2)] !=gastos34[1:length(nrow(gastos34)-2)])


# Uno los dos datasets
datos <- merge(gastos12,gastos34, by = c(colnames(gastos12[1:4])))
```

```{r}
unique(datos$`Tipo de dato`)

# Nos quedamos únicamente con los datos base, quitando las tasas de variación
datos <- subset(datos, datos$`Tipo de dato`== unique(datos$`Tipo de dato`)[1])
# Quito la columna irrelevante
datos <- subset(datos, select = -`Tipo de dato`)
```

## Transformación de clases

```{r}
lapply(datos,class)
```


```{r}
# Quitar punto de miles
datos[, 4:ncol(datos)] <- lapply(datos[, 4:ncol(datos)], function(x) gsub("\\.", "", x))
# Sustituir coma decimal por punto decimal
datos[, 4:ncol(datos)] <- lapply(datos[, 4:ncol(datos)], function(x) gsub(",", ".", x))
# Transformar a numerico
datos[, 4:ncol(datos)] <- lapply(datos[, 4:ncol(datos)], function(x) as.numeric(x))
# Comprobar la clase
lapply(datos,class)
```


```{r}
# Comprobar si hay datos NA
any(is.na(datos))
```




